from __future__ import annotations

from api.route_registry import EndpointSpec, RouterSpec
from api.routes.social_endpoints import (
    add_favorite_endpoint,
    approve_follow_request_endpoint,
    block_user_endpoint,
    blocked_users_endpoint,
    create_comment_endpoint,
    create_meetup_comment_endpoint,
    create_meetup_endpoint,
    create_report_endpoint,
    create_spot_endpoint,
    create_support_ticket_endpoint,
    delete_comment_endpoint,
    delete_meetup_comment_endpoint,
    delete_meetup_endpoint,
    delete_spot_endpoint,
    delete_ticket_endpoint,
    followers_endpoint,
    follow_requests_endpoint,
    follow_user_endpoint,
    following_endpoint,
    list_all_support_tickets_endpoint,
    list_comments_endpoint,
    list_favorites_endpoint,
    list_meetup_comments_endpoint,
    list_meetup_invites_endpoint,
    list_meetup_notifications_endpoint,
    list_meetups_endpoint,
    list_meetups_spots_endpoint,
    list_moderated_users_endpoint,
    list_reports_endpoint,
    list_spots_endpoint,
    moderation_notifications_endpoint,
    profile_read_endpoint,
    profile_update_endpoint,
    reject_follow_request_endpoint,
    remove_favorite_endpoint,
    remove_follower_endpoint,
    respond_meetup_endpoint,
    review_report_endpoint,
    share_spot_endpoint,
    unblock_user_endpoint,
    unfollow_user_endpoint,
    update_comment_endpoint,
    update_meetup_comment_endpoint,
    update_meetup_endpoint,
    update_spot_endpoint,
    update_ticket_status_endpoint,
    update_user_status_endpoint,
    user_favorites_endpoint,
    user_profile_endpoint,
    user_search_endpoint,
    user_spots_endpoint,
)
from core.social import social_lifespan
from models.schemas import (
    BlockRef,
    FavoriteRef,
    FollowRef,
    FollowRequestRef,
    MeetupComment,
    MeetupInviteRef,
    MeetupNotificationPublic,
    MeetupPublic,
    ModerationNotificationPublic,
    ModerationReportPublic,
    ModerationUserPublic,
    SpotComment,
    SpotPublic,
    SupportTicketPublic,
    UserPublic,
)


def get_social_router_spec() -> RouterSpec:
    return RouterSpec(
        prefix="/social",
        tags=("Social",),
        lifespan=social_lifespan,
        endpoints=(
            EndpointSpec("GET", "/me", profile_read_endpoint, response_model=UserPublic),
            EndpointSpec("PUT", "/me", profile_update_endpoint, response_model=UserPublic),
            EndpointSpec("GET", "/users/search", user_search_endpoint, response_model=list[UserPublic]),
            EndpointSpec("GET", "/users/{user_id}/profile", user_profile_endpoint, response_model=UserPublic),
            EndpointSpec("POST", "/spots", create_spot_endpoint, response_model=SpotPublic),
            EndpointSpec("GET", "/spots", list_spots_endpoint, response_model=list[SpotPublic]),
            EndpointSpec("PUT", "/spots/{spot_id}", update_spot_endpoint, response_model=SpotPublic),
            EndpointSpec("DELETE", "/spots/{spot_id}", delete_spot_endpoint),
            EndpointSpec("GET", "/users/{user_id}/spots", user_spots_endpoint, response_model=list[SpotPublic]),
            EndpointSpec("POST", "/favorites/{spot_id}", add_favorite_endpoint),
            EndpointSpec("GET", "/favorites", list_favorites_endpoint, response_model=list[FavoriteRef]),
            EndpointSpec("DELETE", "/favorites/{spot_id}", remove_favorite_endpoint),
            EndpointSpec("GET", "/users/{user_id}/favorites", user_favorites_endpoint, response_model=list[FavoriteRef]),
            EndpointSpec("POST", "/follow/{user_id}", follow_user_endpoint),
            EndpointSpec("DELETE", "/follow/{user_id}", unfollow_user_endpoint),
            EndpointSpec("GET", "/follow/requests", follow_requests_endpoint, response_model=list[FollowRequestRef]),
            EndpointSpec("POST", "/follow/requests/{follower_id}/approve", approve_follow_request_endpoint),
            EndpointSpec("POST", "/follow/requests/{follower_id}/reject", reject_follow_request_endpoint),
            EndpointSpec("GET", "/followers/{user_id}", followers_endpoint, response_model=list[FollowRef]),
            EndpointSpec("GET", "/following/{user_id}", following_endpoint, response_model=list[FollowRef]),
            EndpointSpec("DELETE", "/followers/{user_id}", remove_follower_endpoint),
            EndpointSpec("POST", "/block/{user_id}", block_user_endpoint),
            EndpointSpec("DELETE", "/block/{user_id}", unblock_user_endpoint),
            EndpointSpec("GET", "/blocked", blocked_users_endpoint, response_model=list[BlockRef]),
            EndpointSpec("POST", "/share/{spot_id}", share_spot_endpoint),
            EndpointSpec("POST", "/support/tickets", create_support_ticket_endpoint, response_model=SupportTicketPublic, status_code=201),
            EndpointSpec("GET", "/support/tickets/admin/all", list_all_support_tickets_endpoint, response_model=list[SupportTicketPublic]),
            EndpointSpec("PATCH", "/support/tickets/{ticket_id}/status", update_ticket_status_endpoint, response_model=SupportTicketPublic),
            EndpointSpec("DELETE", "/support/tickets/{ticket_id}", delete_ticket_endpoint),
            EndpointSpec("POST", "/reports", create_report_endpoint, response_model=ModerationReportPublic, status_code=201),
            EndpointSpec("GET", "/notifications", moderation_notifications_endpoint, response_model=list[ModerationNotificationPublic]),
            EndpointSpec("GET", "/admin/reports", list_reports_endpoint, response_model=list[ModerationReportPublic]),
            EndpointSpec("PATCH", "/admin/reports/{report_id}", review_report_endpoint, response_model=ModerationReportPublic),
            EndpointSpec("GET", "/admin/users", list_moderated_users_endpoint, response_model=list[ModerationUserPublic]),
            EndpointSpec("PATCH", "/admin/users/{user_id}", update_user_status_endpoint, response_model=ModerationUserPublic),
            EndpointSpec("POST", "/spots/{spot_id}/comments", create_comment_endpoint, response_model=SpotComment, status_code=201),
            EndpointSpec("GET", "/spots/{spot_id}/comments", list_comments_endpoint, response_model=list[SpotComment]),
            EndpointSpec("PATCH", "/comments/{comment_id}", update_comment_endpoint, response_model=SpotComment),
            EndpointSpec("DELETE", "/comments/{comment_id}", delete_comment_endpoint),
            EndpointSpec("POST", "/meetups", create_meetup_endpoint, response_model=MeetupPublic, status_code=201),
            EndpointSpec("GET", "/meetups", list_meetups_endpoint, response_model=list[MeetupPublic]),
            EndpointSpec("PUT", "/meetups/{meetup_id}", update_meetup_endpoint, response_model=MeetupPublic),
            EndpointSpec("DELETE", "/meetups/{meetup_id}", delete_meetup_endpoint),
            EndpointSpec("GET", "/meetups/invites", list_meetup_invites_endpoint, response_model=list[MeetupInviteRef]),
            EndpointSpec("POST", "/meetups/{meetup_id}/respond", respond_meetup_endpoint, response_model=MeetupInviteRef),
            EndpointSpec("GET", "/meetups/{meetup_id}/comments", list_meetup_comments_endpoint, response_model=list[MeetupComment]),
            EndpointSpec("POST", "/meetups/{meetup_id}/comments", create_meetup_comment_endpoint, response_model=MeetupComment, status_code=201),
            EndpointSpec("PATCH", "/meetup-comments/{comment_id}", update_meetup_comment_endpoint, response_model=MeetupComment),
            EndpointSpec("DELETE", "/meetup-comments/{comment_id}", delete_meetup_comment_endpoint),
            EndpointSpec("GET", "/meetup-notifications", list_meetup_notifications_endpoint, response_model=list[MeetupNotificationPublic]),
            EndpointSpec("GET", "/meetups/spots", list_meetups_spots_endpoint, response_model=list[SpotPublic]),
        ),
    )
